apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
        - name: database
          image: mongo:latest  # Replace with your database image
          ports:
            - containerPort: 27017  # Default MongoDB port
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: "admin"  # Replace with your database username
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: "password123"  # Replace with your database password

